//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int clientid { get; set; }
        public string clientname { get; set; }
        public string clientaddress { get; set; }
        public string clientnumber { get; set; }
        public string clientemail { get; set; }
        public string note { get; set; }
        public string company { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string img { get; set; }
    }
}
