//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.salesbilldetails = new HashSet<salesbilldetail>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public string productcode { get; set; }
        public decimal price { get; set; }
        public int quantity { get; set; }
        public string note { get; set; }
        public string img { get; set; }
        public Nullable<int> categoryid { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesbilldetail> salesbilldetails { get; set; }
    }
}
