//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesbilldetail
    {
        public int id { get; set; }
        public int productid { get; set; }
        public int salesbillid { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public decimal totalprice { get; set; }
    
        public virtual salesBill salesBill { get; set; }
        public virtual product product { get; set; }
    }
}
