//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salesBill()
        {
            this.salesbilldetails = new HashSet<salesbilldetail>();
        }
    
        public int id { get; set; }
        public int customerid { get; set; }
        public int userid { get; set; }
        public string note { get; set; }
        public double total { get; set; }
        public double discount { get; set; }
        public double netTotal { get; set; }
        public int billNumber { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual client client { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesbilldetail> salesbilldetails { get; set; }
    }
}
