//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int supplierid { get; set; }
        public string suppliername { get; set; }
        public string supplieraddress { get; set; }
        public string suppliernumber { get; set; }
        public string supplieremail { get; set; }
        public string note { get; set; }
        public string company { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string img { get; set; }
    }
}
